# Page settings
baseurl = "https://callab.github.io/"
title = "Communication and Learning Lab"
languageCode = "en-us"
theme = "hugo-elate-theme"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

# Can add background image in themes/hugo-elate-theme/layouts/partials/hero.html or replace full_image_2.jpg
# Adjust transparency in style.css (search 'opacity:')

[params]

  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = "Josef Klafka"
  description = "CaLLab homepage"
  email = "jklafka@andrew.cmu.edu"
  # Navigation
  [params.navigation]
    brand = "Communication and Learning Lab"
    home = "Our Research"
    work = "Releases"
    testimonials = "Lab Friends" # I commented out this tab in partials/nav.html so it isn't displayed
    services = "Join our lab!"
    about = "Lab Members" #Order of this one changed in layouts/partials/nav.html
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order

    # prepended links
#    [[menu.prepend]]
#      url = "http://gohugo.io"
#      name = "Hugo"
#      weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10

# Can edit the order of components in layouts/index.html, and menu order in layouts/partials/nav.html

  # Hero section
  [params.hero]
    title = ""
    subtitle = ''

  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]
    description = """Young children learn the meanings of thousands of words by the time they can run down the street. The computational problem they solve is daunting: extracting discrete word forms from a sequence of continuous speech signals and mapping these forms onto their meanings. Yet, the same children who solve this problem continuously forget where they left their coats and hats. How do children learn language so quickly despite cognitive constraints on memory, attention, and information processing? <br> <br>
                  Our work tries to resolve this puzzle by reframing language acquisition as a coordination problem. The problem is not how children learn language, but how parents and children construct it together. <br> <br>
                  We analyze this coordination by taking an end-to-end approach to understanding early language acquisition, studying it at multiple levels. Our first line of work investigates the representations and algorithms that children and adults bring to the learning problem. Our second line of work investigates the natural ecological contexts in which language acquisition occurs. Finally, our third line of work uses computational models to formalize the interactions between learner and environment. Successes and failures of language learning emerge from the match (or mismatch) between the learning mechanisms available to the child and the structure of the learning environment."""

  [[params.intro.item]]
    title = "Experimental Studies"
#    description = "Check out publications and/or preprints from the lab. We ensure all our work is available to the public, so if you can't find a paper let us know!"
#    url = "https://osf.io/preprints/discover?provider=OSFORPsyArXiv&q=tags%3A(%22corelab%22)&sort=-date_updated" #Searches for OSF Preprints and PsyArXiv preprints, with the tag "corelab", sorted from most recent -> oldest.
#    button = "Access Papers"
    icon = "icon-speech"
    img = "ipad_task.jpg"

  [[params.intro.item]]
    title = "Naturalistic Observation"
#    description = "To the extent possible we make materials, data, and analysis scripts publicly available on the Open Science Framework. These may be used for re-analysis or for novel hypotheses."
#    url = 'https://osf.io/search/?q=tags:(corelabdat)&page=1' #Searches for projects tagged "corelabdat".
#    button = "Find our datasets"
    icon = "icon-magnifier-add"
    img = "toy_play.png"

  [[params.intro.item]]
    title = "Computational Models"
#    description = "Doing science is really hard. Here, we document the workflow of the lab and expectations for lab members. Includes templates for OSF projects to make open science easier."
#    url = "https://docs.google.com/document/d/1aZWfCIReB9goSiEQcYQGWj70R0NXfQ0cOWKWa3julcA/edit?usp=sharing" #the file is under /content/
#    button = "Download"
    icon = "icon-graph"
    img = "lba_mod.png"

  [param.intro.text]
    text = "hello world"

  [params.intro.news] #did some heavy editing of params/intro.html to add this section
    enable = false
    title = "Announcements"
    description = '&bull; Find slides and presentations from our recent Open Science workshop in Bordeaux <a href="https://osf.io/gvkxn/">here</a>.<br>&bull; We sent off three members of the lab who have completed very successful internships: Justin, Armel, and Mehdi. <br>&bull; Hans IJzerman has signed a contract with <a href="https://en.wikipedia.org/wiki/W._W._Norton_%26_Company">WW Norton</a> to write a popular science book on thermoregulation in social relationships<br>&bull; <a href="https://psyarxiv.com/785qu/">Last submitted manuscript</a> was for the Psych Science Accelerator'

# Above description is less tidy than the rest because I hacked it in to the intro. Will try to tidy it later.

  [params.intro.video]
    enable = false
    title = "Watch the video."
    icon = "icon-play2"
    url = "https://vimeo.com/channels/staffpicks/93951774"


  # Work section
# To enable external URLs here, I had to edit layouts/partials/work.html.
# Line 16 from: <a href="images/{{ .img }}" class="fh5co-project-item image-popup to-animate">
# to: <a href="{{ .url }}" class="fh5co-project-item to-animate">
# Also edited work.html to add the 'category' images. Can add new ones or change current
# just edit with Gimp releases_categories.xcf (in images folder) and save as "name.png".
# Can remove entirely by deleting this line from work.html: <img src="images/{{ .category }}" class="img-responsive">

  [params.work]
    enable = false
    title = "Releases"
    description = "Here are recent projects we've completed."
    footertext = "We're working on a page for achived projects. We'll link those here when it's ready."

    [[params.work.row]]
      category = "announcements.png"
      img = "philo_update_2019.png"
      alt = "Workflow Update"
      title = "Annual Workflow Update"
      subtitle = "9/2019 - We've released the 2019 update to our lab philosophy/workflow. Key changes: Sprints, CRediT contributorship, code hygeine."
      url = "https://docs.google.com/document/d/1aZWfCIReB9goSiEQcYQGWj70R0NXfQ0cOWKWa3julcA/edit?usp=sharing"

    [[params.work.row]]
      category = "conference.png"
      img = "annecy.png"
      alt = "Tech and Relationships"
      title = "Tech and Relationships Conference"
      subtitle = "5/2019 - We're organizing an EASP conference and Facebook+AdopteUnMec Hackathon in Annecy, France."
      url = "https://www.techandrelationships.org"

    [[params.work.row]]
      category = "education.png"
      img = "osworkshop.png"
      alt = "Open Science Workshop"
      title = "Open Science Workshop"
      subtitle = "4/2019 - We're giving a workshop on the Open Science Framework, and a deep dive on power analysis."
      url = "https://osf.io/gvkxn/"

    [[params.work.row]]
      category = "publication.png"
      img = "ml2.png" # these images should go in themes/hugo-elate-theme/static/images/ and be 470x330 pixels
      alt = "ml2 image"
      title = "Many Labs 2"
      subtitle = "12/2018 - 135 labs around the world replicate 28 studies. Find minimal variation in results depending on the sample."
      url = "https://journals.sagepub.com/doi/10.1177/2515245918810225"

    [[params.work.row]]
      category = "preprint.png"
      img = "straq1.png"
      alt = "straq-1"
      title = "STRAQ-1"
      subtitle = "10/2018 - Developing a scale to measure individual differences in social thermoregulation."
      url = "https://psyarxiv.com/6b7ne"

    [[params.work.row]]
      category = "education.png"
      img = "bord_workshop.png"
      alt = "Solid Science"
      title = "Solid Science Training Workshop"
      subtitle = "9/2018 - We organized a workshop training scientists on doing reproducible, open science. Videos and materials available on the OSF."
      url = "https://osf.io/gvkxn/"

    [[params.work.row]]
      category = "publication.png"
      img = "penguins-429128_1920.jpg"
      alt = "Penguins Image"
      title = "Human Penguin Project"
      subtitle = "9/2018 - International collaboration investigating the link between social environment and core body temperature."
      url = "https://psyarxiv.com/6b7ne"

    [[params.work.row]]
      category = "publication.png"
      img = "cup-939479_1920.jpg"
      alt = "Cold Glass Image"
      title = "Socially Thermoregulated Thinking"
      subtitle = "8/2018 - Past experiences, and a current manipulation of physical temperature, affect thinking about our loved ones."
      url = "https://psyarxiv.com/25dmj"

      [[params.work.row]]
      category = "publication.png"
      img = "oxford.jpg"
      alt = "Oxford Image"
      title = "Oxford Bibliography Guide"
      subtitle = "5/2018 - Two of our researchers participated in a collaboration to write an Oxford Bibliography on replication initiatives in psychology."
      url = "https://psyarxiv.com/h5jm7/"

#    [[params.work.row]]
#      category = "publication.png"
#      img = "transparency.jpg"
#      alt = "Transparency Image"
#      title = "Transparency Guide"
#      subtitle = "6/2018 - One of our researchers participated in a collaboration to write a practical guide for more transparent science."
#      url = "https://psyarxiv.com/rtygm"

#    [[params.work.row]]
#      category = "preprint.png"
#      img = "stroopml.png"
#      alt = "Stroop figure"
#      title = "Machine Learning and the Stroop Effect"
#      subtitle = "5/2017 - Revisiting what predicts performance on a classic effect using new statistics (conditional random forests)."
#      url = "https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2805205"

  # About section
  # Edited about.html to fix display issues when adding 6+ collaborators
  [params.about]
    enable = true
    title = "Lab Members"
#    footertext = '<big>Former members:</big> <a href="https://osf.io/n75jp/">Lison Neyroud</a>, <a href="http://armelsoubeiga.ga/">Armel Soubeiga</a>, Justin Mah, <a href="https://github.com/souabniMehdi">Mehdi Souabni</a>, <a href="https://osf.io/qetx7/">Nazanin Kafaee</a>, <a href="https://www.researchgate.net/profile/Elisa_Sarda">Elisa Sarda</a>.'
#    description = ""

  [[params.about.item]]
    name = '<a href="http://www.thoughtfill.com/">Daniel Yurovsky</a>'
    position = 'Principal Investigator'
    description = "Dan was an undergrad computer science major at Carnegie Mellon before completing a PhD in Cognitive Psychology at Indiana University and doing a postdoc in Psych Department at Stanford. He is broadly interested in how we learn from the people around us, and especially how children learn language. Dan is excited about understanding communication and learning from a systems perspective."
    img = "yurovsky.jpg"  # 300x300 images in themes/hugo-elate-theme/static/images/
    alt = "DanYurovsky"
    social = [
      ["icon-globe", "http://www.thoughtfill.com"],
      ["icon-folder", "https://osf.io/yaxc8/"],
      ["icon-google", "https://scholar.google.com/citations?user=DYSp4-kAAAAJ&hl"],
      ["icon-twitter", "https://twitter.com/danyurovsky"],
      ["icon-github", "https://github.com/dyurovsky"]
    ]

  [[params.about.item]]
    name = '<a href="https://jklafka.github.io/">Josef Klafka</a>'
    position = "Lab Manager"
    description = "Joe did his undergrad at UChicago in math and linguistics. He is interested in how children learn new words and grammar, and applications to machine learning."
    img = "klafka.jpg"
    alt = "JosefKlafka"
    social = [
      ["icon-globe", "https://jklafka.github.io/"],
      ["icon-twitter", "https://twitter.com/josefklafka"],
      ["icon-github", "https://github.com/jklafka"]
    ]

# Below used to bug out after 5 people, I think I fixed it in about.html though
    [[params.about.item]]
      name = 'Claire Bergey'
      position = "PhD Student"
      description = "Claire is a third-year PhD student in the Cognition program at the University of Chicago. She studied psychology and cognitive science at Williams College. She is interested in language and category acquisition."
      img = "bergey.jpg"
      alt = "Patrick"
      social = [
        ["icon-globe", "https://www.researchgate.net/profile/Patrick_Forscher"],
      ]

    [[params.about.item]]
      name = 'Ashley Leung'
      position = "PhD Student"
      description = "Ashley is a second-year PhD student in Psychology at the University of Chicago. She graduated from Middlebury College with a BA in Psychology and English & American Literatures. She is broadly interested in child language acquisition, and she is currently studying how parent-child communication influences language learning."
      img = "leung.jpg"
      alt = "Alessandro"
      social = [
        ["icon-globe", "https://www.researchgate.net/profile/Alessandro_Sparacio"]
      ]

    [[params.about.item]]
      name = 'Benjamin Morris'
      position = "PhD Student"
      description = "Ben received his Masters in Developmental Psychology at the University of Cambridge working with Claire Hughes. Ben has a B.A. in Psychology from Reed College, where he worked with Jennifer Corpus. He is primarily interested in optimal word learning strategies and their connection to early cognitive development."
      img = "morris.jpg"
      alt = "Ben"
      social = [
        ["icon-globe", "https://www.researchgate.net/profile/Alessandro_Sparacio"]
      ]

    [[params.about.item]]
      name = 'Alexandra Tunkel'
      position = "Honors Thesis Student"
      description = "Alexandra is a fourth-year undergraduate at the University of Chicago, double majoring in Biology and Psychology. She is interested in the application of these two fields in child development."
      img = "tunkel.jpg"
      alt = "Ben"
      social = [
        ["icon-globe", "https://www.researchgate.net/profile/Alessandro_Sparacio"]
      ]

  # Testimonials section
  # I edited partials/testimonials.html to remove the quotes and change this to a friends-of-lab section.
  # Due to this, we add urls with html code (<a href=""></a>). See Below
  # All images need to be square (e.g. 400 x 400) or the spacing of the page will be messed up
  # Also, seems finicky to the length of text. May need to use abbreviations for names/affiliations.

  [params.testimonials]
    enable = true
    title = "Lab Alumni"

    [[params.testimonials.item]]
      person = '<a href="https://jamescoan.com/">Xiuyuan Flora Zhang</a><br> Yale University'
      img = "zhang.jpg"
      alt = "flora" # This is just text that gets displayed if the img file fails to load]

    [[params.testimonials.item]]
      person = '<a href="https://jamescoan.com/">Madeline Meyers</a><br> Stanford University'
      img = "maddie.jpg"
      alt = "maddie" # This is just text that gets displayed if the img file fails to load

    [[params.testimonials.item]]
      person = '<a href="https://jamescoan.com/">Yawen Yu</a><br> University of California, Los Angeles'
      img = "yu.jpg"
      alt = "yawen" # This is just text that gets displayed if the img file fails to load

    [[params.testimonials.item]]
      person = '<a href="https://jamescoan.com/">Emmi Russo</a><br> Microsoft'
      img = "emmi.jpg"
      alt = "emmi" # This is just text that gets displayed if the img file fails to load



  # Services section
  # Note: The description lengths below need to be roughly equal or the formatting will get messed up.
  [params.services]
    enable = true
    title = "Join our lab!"
    description = "We are always looking for motivated, passionate students and researchers to join our team. Please contact us if you have any questions about our work!"


    [[params.services.item]]
      title = "Research Assistants"
      description = "Undergraduate Opportunities: The Communication and Learning Lab has openings for undergraduates to gain research experience working as RAs. As a research assistant in CaLLab, you could be involved in research at every step of the process, from developing research questions and creating stimuli to recruiting subjects and testing participants. If you would like to hear more about working as an RA, please contact our lab manager Joe (jklafka [at] andrew [dot] cmu [dot] edu). "
      icon = "icon-graduation"

    [[params.services.item]]
      title = "Graduate Students"
      description = 'Interested in graduate study at the Carnegie Mellon? Visit the Psychology Department page <a href="https://www.cmu.edu/dietrich/psychology/">here</a> for more information on graduate programs offered and the application process. Please contact Professor Yurovsky (dry [at] andrew [dot] cmu [dot] edu) if you are interested in pursuing graduate research in the Communication and Learning Lab.'
      icon = "icon-graduation"

  # Counters section
  [params.counters]
    enable = false
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Finished projects"
      icon = "icon-briefcase"
      from = 0
      to = 89
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Lines of code"
      icon = "icon-code"
      from = 0
      to = 2343409
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 1302
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Happy clients"
      icon = "icon-people"
      from = 0
      to = 52
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    map = true
    form = true
    title = "Get in touch"
    description = ""

    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "5000 Forbes Ave <br> Pittsburgh, PA 15213"],
#        ["icon-phone", "(123) 465-6789"],
        ["icon-envelope", "callab@andrew.cmu.edu"],
        ["icon-globe", '<a href="https://callab.github.io" target="_blank">CaLLab website</a>']
      ]

    name = "Name"
    email = "Email"
#    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = 'Powered by the <a href="https://github.com/saey55/hugo-elate-theme">Elate Hugo port</a>.<br>Source (blogdown) files for this page and instructions for use are available on <a href="https://github.com/co-relab/co-relab_source">GitHub</a>'
#    links = [
#        ["icon-twitter", "#twitter"],
#        ["icon-facebook", "#facebook"],
#        ["icon-youtube", "#youtube"]
#      ]

# Note: to enable the map you may need to insert your own API key into layouts/partials/js.html
# Currently we're using Rick's API key
# To replace see https://github.com/saey55/hugo-elate-theme/issues/37#issuecomment-428863867
